import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    passWithNoTests: false,
    projects: [
      {
        test: {
          include: ["packages/**/*.unit.test.ts"],
          name: "unit",
        },
      },
      {
        test: {
          include: ["tests/**/*.integration.test.ts"],
          name: "integration",
        },
      },
    ],
    coverage: {
      clean: true,
      exclude: ["packages/test-kit/src/index.ts"],
      include: [
        "packages/cli/src/command-router.ts",
        "packages/cli/src/library-api.ts",
        "packages/cli/src/documentation-artifacts.ts",
        "packages/cli/src/process-cli.ts",
        "packages/cli/src/i03-commands.ts",
        "packages/cli/src/efficiency-command.ts",
        "packages/cli/src/git-metadata-executor.ts",
        "packages/cli/src/git-metadata-executor-production.ts",
        "packages/core/src/compatibility-policy.ts",
        "packages/core/src/configuration-contracts.ts",
        "packages/core/src/configuration-validation.ts",
        "packages/core/src/contract-validation.ts",
        "packages/core/src/diagnostic-contracts.ts",
        "packages/core/src/diagnostic-baseline.ts",
        "packages/core/src/diagnostic-fingerprint.ts",
        "packages/core/src/diagnostic-validation.ts",
        "packages/core/src/ir-contracts.ts",
        "packages/core/src/ir-validation.ts",
        "packages/core/src/output-contracts.ts",
        "packages/core/src/output-validation.ts",
        "packages/core/src/organization-policy.ts",
        "packages/core/src/output-sanitization.ts",
        "packages/formatters/src/**/*.ts",
        "packages/core/src/profile-contracts.ts",
        "packages/core/src/profile-validation.ts",
        "packages/core/src/repository-path.ts",
        "packages/evidence/src/read-only-filesystem.ts",
        "packages/evidence/src/atomic-writer.ts",
        "packages/evidence/src/safe-fix-pipeline.ts",
        "packages/evidence/src/repository-root.ts",
        "packages/evidence/src/ignore-engine.ts",
        "packages/evidence/src/discovery-index.ts",
        "packages/evidence/src/import-graph-loader.ts",
        "packages/evidence/src/evidence-index.ts",
        "packages/evidence/src/command-lexer.ts",
        "packages/evidence/src/statement-classifier.ts",
        "packages/evidence/src/duplication-index.ts",
        "packages/evidence/src/workspace-boundary-discovery.ts",
        "packages/efficiency/src/estimate-tokenizer.ts",
        "packages/efficiency/src/exact-tokenizer-artifact.ts",
        "packages/efficiency/src/exact-tokenizer.ts",
        "packages/efficiency/src/context-efficiency-metrics.ts",
        "packages/efficiency/src/context-efficiency-score.ts",
        "packages/efficiency/src/context-efficiency-recommendations.ts",
        "packages/efficiency/src/context-efficiency-report.ts",
        "packages/efficiency/src/efficiency-score-specification.ts",
        "packages/efficiency/src/occurrence-token-accounting.ts",
        "packages/efficiency/src/profile-target-distribution.ts",
        "packages/efficiency/src/tokenizer-contract.ts",
        "packages/evidence/src/tracked-file-enumeration.ts",
        "packages/evidence/src/changed-file-metadata.ts",
        "packages/markdown/src/**/*.ts",
        "packages/profiles/src/copilot.ts",
        "packages/profiles/src/claude-code.ts",
        "packages/profiles/src/cursor.ts",
        "packages/profiles/src/glob-dialects.ts",
        "packages/resolver/src/activation-algebra.ts",
        "packages/resolver/src/bounded-resolution.ts",
        "packages/resolver/src/canonical-policy-sync.ts",
        "packages/resolver/src/copilot-profile.ts",
        "packages/resolver/src/claude-code-profile.ts",
        "packages/resolver/src/cross-profile-comparison.ts",
        "packages/resolver/src/cursor-profile.ts",
        "packages/resolver/src/document-import-dag.ts",
        "packages/resolver/src/instruction-list.ts",
        "packages/resolver/src/effective-context.ts",
        "packages/resolver/src/effective-context-cache.ts",
        "packages/resolver/src/explain-projection.ts",
        "packages/resolver/src/profile-glob-dialects.ts",
        "packages/resolver/src/resolution-event-trace.ts",
        "packages/resolver/src/target-sampler.ts",
        "packages/rules/src/registry.ts",
        "packages/rules/src/mechanical-fix-safety-data.ts",
        "packages/rules/src/mechanical-fix-safety.ts",
        "packages/rules/src/conflicts-duplication.ts",
        "packages/rules/src/context-efficiency.ts",
        "packages/rules/src/portability.ts",
        "packages/rules/src/repository-drift.ts",
        "packages/rules/src/rule-scheduler.ts",
        "packages/rules/src/changed-file-mode.ts",
        "packages/rules/src/semantic-plugin.ts",
        "packages/rules/src/document-context.ts",
        "packages/rules/src/scope-activation.ts",
        "packages/rules/src/security.ts",
        "packages/rules/src/syntax-structure.ts",
        "packages/rules/src/standards-freshness.ts",
        "packages/syntax/src/configuration-parser.ts",
        "packages/syntax/src/configuration-resolution.ts",
        "packages/syntax/src/agents-markdown.ts",
        "packages/syntax/src/copilot-instructions.ts",
        "packages/syntax/src/claude-instructions.ts",
        "packages/syntax/src/cursor-rules.ts",
        "packages/syntax/src/frontmatter-parser.ts",
        "packages/syntax/src/import-lexer.ts",
        "packages/syntax/src/suppression.ts",
        "packages/standards/src/knowledge-pack.ts",
        "packages/standards/src/bundled-pack-loader.ts",
        "packages/standards/src/standards-cache.ts",
        "packages/standards/src/registry-client.ts",
        "packages/standards/src/standards-check.ts",
        "packages/standards/src/standards-update.ts",
        "packages/standards/src/tuf-trust.ts",
        "packages/test-kit/src/**/*.ts",
      ],
      provider: "v8",
      reporter: ["text", "json", "json-summary"],
      reportsDirectory: "coverage",
      thresholds: {
        branches: 90,
        functions: 95,
        lines: 95,
        statements: 95,
      },
    },
  },
});
