import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import test from "node:test";

import { buildOfficialExampleCorpus } from "./generate-official-example-corpus.mjs";

const REPOSITORY_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const TOOL = path.join(REPOSITORY_ROOT, "tools/conformance/generate-official-example-corpus.mjs");

function digest(value) {
  return createHash("sha256").update(value).digest("hex");
}

test("generator deterministically emits one polarity pair per GA surface", async () => {
  const first = await buildOfficialExampleCorpus(REPOSITORY_ROOT);
  const second = await buildOfficialExampleCorpus(REPOSITORY_ROOT);
  assert.equal(first.size, 16);
  assert.deepEqual([...first.keys()], [...second.keys()]);
  for (const [name, bytes] of first) assert.ok(bytes.equals(second.get(name)), name);

  const manifest = JSON.parse(
    first.get("conformance/official-examples/v0/corpus.json").toString("utf8"),
  );
  assert.equal(manifest.fixtures.length, 14);
  assert.equal(manifest.capabilities.length, 22);
  assert.equal(manifest.capabilities.length * 2, 44);
  assert.deepEqual(new Set(manifest.fixtures.map((fixture) => fixture.surfaceId)).size, 7);
  for (const reference of manifest.fixtures) {
    const bytes = first.get(reference.path);
    assert.ok(bytes, reference.path);
    assert.equal(reference.sha256, digest(bytes));
    const fixture = JSON.parse(bytes.toString("utf8"));
    assert.equal(fixture.provenance.derivation, "official-example");
    assert.equal(fixture.extensions["agent-context-lint.dev/k01"].polarity, reference.polarity);
  }
});

test("checked-in generated bytes are current", async () => {
  const outputs = await buildOfficialExampleCorpus(REPOSITORY_ROOT);
  for (const [relative, expected] of outputs) {
    assert.ok(readFileSync(path.join(REPOSITORY_ROOT, ...relative.split("/"))).equals(expected));
  }
});

test("CLI check succeeds while mutation requires explicit review acknowledgement", () => {
  const check = spawnSync(process.execPath, [TOOL, "--check"], {
    cwd: REPOSITORY_ROOT,
    encoding: "utf8",
  });
  assert.equal(check.status, 0, check.stderr);
  assert.match(check.stdout, /valid 16 generated/u);

  const unacknowledged = spawnSync(process.execPath, [TOOL, "--write"], {
    cwd: REPOSITORY_ROOT,
    encoding: "utf8",
  });
  assert.equal(unacknowledged.status, 2);
  assert.match(unacknowledged.stderr, /acknowledge-reviewed-update/u);

  const unknown = spawnSync(process.execPath, [TOOL, "--network"], {
    cwd: REPOSITORY_ROOT,
    encoding: "utf8",
  });
  assert.equal(unknown.status, 2);
  assert.match(unknown.stderr, /usage:/u);

  const ambiguous = spawnSync(
    process.execPath,
    [TOOL, "--check", "--write", "--acknowledge-reviewed-update"],
    { cwd: REPOSITORY_ROOT, encoding: "utf8" },
  );
  assert.equal(ambiguous.status, 2);
  assert.match(ambiguous.stderr, /usage:/u);
});
