# Generated by scripts/generate-cli-documentation.mjs. Do not edit.
_agent_context_lint() {
  local current previous command
  COMPREPLY=()
  current="${COMP_WORDS[COMP_CWORD]}"
  previous="${COMP_WORDS[COMP_CWORD-1]}"
  command="${COMP_WORDS[1]}"
  case "$command:$previous" in
    efficiency:--agent) COMPREPLY=( $(compgen -W 'claude-code codex-cli copilot-cli copilot-cloud-agent copilot-code-review copilot-vscode cursor-agent gemini-cli' -- "$current") ); return ;;
    efficiency:--format) COMPREPLY=( $(compgen -W 'terminal json' -- "$current") ); return ;;
    efficiency:--compare) COMPREPLY=( $(compgen -d -- "$current") ); return ;;
    efficiency:--width) COMPREPLY=(); return ;;
    explain:--agent) COMPREPLY=( $(compgen -W 'claude-code codex-cli copilot-cli copilot-cloud-agent copilot-code-review copilot-vscode cursor-agent gemini-cli' -- "$current") ); return ;;
    explain:--trace) COMPREPLY=( $(compgen -f -- "$current") ); return ;;
    explain:--surface) COMPREPLY=( $(compgen -W 'cursor-agent/cli cursor-agent/ide' -- "$current") ); return ;;
    explain:--format) COMPREPLY=( $(compgen -W 'terminal json' -- "$current") ); return ;;
    list:--format) COMPREPLY=( $(compgen -W 'terminal json' -- "$current") ); return ;;
    rules:--format) COMPREPLY=( $(compgen -W 'terminal json' -- "$current") ); return ;;
    scan:--format) COMPREPLY=( $(compgen -W 'stylish json sarif' -- "$current") ); return ;;
    scan:--rule) COMPREPLY=(); return ;;
    scan:--severity) COMPREPLY=(); return ;;
    scan:--fail-on) COMPREPLY=( $(compgen -W 'error warning never' -- "$current") ); return ;;
    scan:--maximum-concurrency) COMPREPLY=(); return ;;
    scan:--profile) COMPREPLY=( $(compgen -W 'claude-code codex-cli copilot-cli copilot-cloud-agent copilot-code-review copilot-vscode cursor-agent gemini-cli' -- "$current") ); return ;;
    scan:--surface) COMPREPLY=( $(compgen -W 'claude-code/local-session codex-cli/local-cli-single-cwd copilot-cli/local-terminal copilot-cloud-agent/github-hosted copilot-code-review/github-hosted copilot-vscode/local-chat cursor-agent/cli cursor-agent/ide gemini-cli/local-terminal' -- "$current") ); return ;;
    scan:--base) COMPREPLY=(); return ;;
    standards:--format) COMPREPLY=( $(compgen -W 'terminal json' -- "$current") ); return ;;
    standards:--cache) COMPREPLY=( $(compgen -d -- "$current") ); return ;;
  esac
  if (( COMP_CWORD == 1 )); then
    COMPREPLY=( $(compgen -W 'efficiency explain init list rules scan standards -h --help -V --version' -- "$current") )
    return
  fi
  case "$command" in
    efficiency)
      if [[ "$current" == -* ]]; then COMPREPLY=( $(compgen -W '-h --help --agent --format --compare --no-color --width' -- "$current") ); else COMPREPLY=( $(compgen -d -- "$current") ); fi ;;
    explain)
      if [[ "$current" == -* ]]; then COMPREPLY=( $(compgen -W '-h --help --agent --trace --surface --format' -- "$current") ); else COMPREPLY=( $(compgen -f -- "$current") ); fi ;;
    init)
      if [[ "$current" == -* ]]; then COMPREPLY=( $(compgen -W '-h --help' -- "$current") ); else COMPREPLY=( $(compgen -d -- "$current") ); fi ;;
    list)
      if [[ "$current" == -* ]]; then COMPREPLY=( $(compgen -W '-h --help --format' -- "$current") ); else COMPREPLY=( $(compgen -d -- "$current") ); fi ;;
    rules)
      if [[ "$current" == -* ]]; then COMPREPLY=( $(compgen -W '-h --help --format' -- "$current") ); else COMPREPLY=(); fi ;;
    scan)
      if [[ "$current" == -* ]]; then COMPREPLY=( $(compgen -W '-h --help --format --rule --severity --fail-on --maximum-concurrency --profile --surface --changed --base --fix-dry-run' -- "$current") ); else COMPREPLY=( $(compgen -d -- "$current") ); fi ;;
    standards)
      if [[ "$current" == -* ]]; then COMPREPLY=( $(compgen -W '-h --help --format --cache --dry-run' -- "$current") ); else COMPREPLY=( $(compgen -W 'check status update' -- "$current") ); fi ;;
  esac
}
complete -F _agent_context_lint agent-context-lint
