/** Stable package identifier for diagnostics and composition metadata. */
export const packageId = "@agent-context/core" as const;

export * from "./repository-path.js";

export {
  CONFIGURATION_CONTRACT_VERSION,
  CONFIGURATION_FILE_NAME,
  CONFIGURATION_PROFILE_IDS,
  CONFIGURATION_PROFILE_KEYS,
  CONFIGURATION_PROFILE_KEY_BY_ID,
  CONFIGURATION_RULE_SEVERITIES,
  CONFIGURATION_SOURCE_LIMITS,
  CONFIGURATION_SURFACE_IDS,
  CONFIGURATION_SURFACES_BY_PROFILE,
  CONFIGURATION_UNKNOWN_KEY_POLICY,
  CONFIGURATION_VALUE_LIMITS,
  DEFAULT_AGENT_CONTEXT_CONFIGURATION,
  EFFICIENCY_COMPONENT_KEYS,
  EFFICIENCY_SCORE_VERSIONS,
  EFFICIENCY_TOKENIZERS,
  PACKAGE_MANAGERS,
  STANDARDS_CHANNELS,
  appendConfigurationPathProperty,
} from "./configuration-contracts.js";
export { validateAgentContextConfiguration } from "./configuration-validation.js";
export type {
  AgentContextConfiguration,
  ConfigurationProfileId,
  ConfigurationProfileKey,
  ConfigurationRuleSeverity,
  ConfigurationSourceLocation,
  ConfigurationSourceLimits,
  ConfigurationSourcePosition,
  ConfigurationSourceRange,
  ConfigurationSurfaceId,
  ConfigurationUnknownKeyPolicy,
  ConfigurationValueLimits,
  ConfigurationValidationCode,
  ConfigurationValidationIssue,
  ConfigurationValidationResult,
  EfficiencyComponentKey,
  EfficiencyScoreVersion,
  EfficiencyTokenizer,
  PackageManager,
  ProfileConfiguration,
  ResourceLimitConfiguration,
  RuleConfiguration,
  StandardsChannel,
} from "./configuration-contracts.js";
export type { ConfigurationValidationOptions } from "./configuration-validation.js";

export {
  ORGANIZATION_POLICY_AUTHORITIES,
  ORGANIZATION_POLICY_LIMITS,
  ORGANIZATION_POLICY_PACK_SCHEMA_VERSION,
  ORGANIZATION_POLICY_SETTING_IDS,
  ORGANIZATION_POLICY_TARGET_KINDS,
  classifyOrganizationPolicyTarget,
  resolveOrganizationPolicy,
  validateOrganizationPolicyPack,
} from "./organization-policy.js";
export type {
  OrganizationPolicyAssignmentSource,
  OrganizationPolicyAuthority,
  OrganizationPolicyCapabilities,
  OrganizationPolicyCompatibility,
  OrganizationPolicyEntry,
  OrganizationPolicyIssue,
  OrganizationPolicyIssueCode,
  OrganizationPolicyLocationProvider,
  OrganizationPolicyOverride,
  OrganizationPolicyOverrideSource,
  OrganizationPolicyPack,
  OrganizationPolicyPackOrigin,
  OrganizationPolicyProvenance,
  OrganizationPolicyResolutionEvent,
  OrganizationPolicyResolutionResult,
  OrganizationPolicyRuleValue,
  OrganizationPolicySettingId,
  OrganizationPolicyTarget,
  OrganizationPolicyTargetClassificationResult,
  OrganizationPolicyTargetKind,
  OrganizationPolicyValidationResult,
  OrganizationPolicyValue,
  ResolveOrganizationPolicyOptions,
  ResolvedOrganizationPolicyAssignment,
  ValidateOrganizationPolicyPackOptions,
  ValidatedOrganizationPolicyPack,
} from "./organization-policy.js";

export {
  DIAGNOSTIC_CONTRACT_VERSION,
  DIAGNOSTIC_SEVERITIES,
  FIX_OPERATION_KINDS,
  PATH_FINGERPRINT_METHOD,
  RELATED_EVIDENCE_KINDS,
  SEMANTIC_FINGERPRINT_METHOD,
  SUPPRESSION_STATES,
} from "./diagnostic-contracts.js";
export { computePathFingerprint, computeSemanticFingerprint } from "./diagnostic-fingerprint.js";
export {
  BASELINE_COMPARISON_STATUSES,
  BASELINE_DIAGNOSTIC_KINDS,
  MAX_BASELINE_PATH_MOVES,
  MAX_BASELINE_SERIALIZED_BYTES,
  baselineValidationIssues,
  compareDiagnosticBaseline,
  computeBaselineProvenanceDigest,
  generateDiagnosticBaseline,
} from "./diagnostic-baseline.js";
export type {
  BaselineComparisonReason,
  BaselineComparisonStatus,
  BaselineComparisonSummary,
  BaselineDiagnosticClassification,
  BaselineDiagnosticComparison,
  BaselineDiagnosticKind,
  BaselineOperationIssue,
  BaselineOperationIssueCode,
  BaselinePathMove,
  BaselineStaleEntry,
  CompareDiagnosticBaselineInput,
  CompareDiagnosticBaselineResult,
  GenerateDiagnosticBaselineInput,
  GenerateDiagnosticBaselineResult,
} from "./diagnostic-baseline.js";
export {
  MAX_DIAGNOSTICS_PER_BUNDLE,
  MAX_DIAGNOSTIC_JSON_CONTAINER_ENTRIES,
  MAX_DIAGNOSTIC_JSON_KEY_BYTES,
  MAX_DIAGNOSTIC_JSON_STRING_BYTES,
  MAX_DIAGNOSTIC_JSON_TOTAL_STRING_BYTES,
  MAX_DIAGNOSTIC_JSON_VALUES,
  MAX_DIAGNOSTIC_TEXT_BYTES,
  MAX_FIX_OPERATIONS_PER_PLAN,
  MAX_FIX_TEXT_BYTES,
  MAX_RELATED_EVIDENCE_PER_DIAGNOSTIC,
  MAX_SUPPRESSIONS_PER_BUNDLE,
  isDiagnosticBundle,
  validateDiagnosticBundle,
} from "./diagnostic-validation.js";
export type {
  AtomicFixPlan,
  CreateDocumentFixOperation,
  Diagnostic,
  DiagnosticBundle,
  DiagnosticContractValidationCode,
  DiagnosticContractValidationIssue,
  DiagnosticContractValidationResult,
  DiagnosticFingerprint,
  DiagnosticFingerprintBasis,
  DiagnosticFingerprints,
  DiagnosticId,
  DiagnosticSeverity,
  DiagnosticSourceLocation,
  DiagnosticSuggestion,
  FingerprintComponent,
  FixOperation,
  FixOperationKind,
  FixPlanId,
  MoveDocumentFixOperation,
  PathFingerprintBasis,
  RelatedEvidence,
  RelatedEvidenceId,
  RelatedEvidenceKind,
  RepositoryFactRelatedEvidence,
  ResolutionEvidenceRef,
  ResolutionRelatedEvidence,
  SemanticFingerprintBasis,
  SourceRelatedEvidence,
  SpecRelatedEvidence,
  SuppressionId,
  SuppressionRecord,
  SuppressionState,
  TextEditFixOperation,
  VersionedFingerprint,
} from "./diagnostic-contracts.js";

export { MAX_VALIDATION_ISSUES, VALIDATION_ISSUE_LIMIT_CODE } from "./contract-validation.js";

export {
  INSTRUCTION_IR_SNAPSHOT_CONTRACT_VERSION,
  INSTRUCTION_IR_SNAPSHOT_LIMITS,
  createInstructionIrSnapshot,
  getInstructionIrSnapshotProvenance,
  isIssuedInstructionIrSnapshot,
} from "./ir-snapshot.js";
export type {
  InstructionIrSnapshot,
  InstructionIrSnapshotCounts,
  InstructionIrSnapshotLimits,
  InstructionIrSnapshotProvenance,
  InstructionIrSnapshotResult,
  InstructionIrSnapshotUsage,
} from "./ir-snapshot.js";

export {
  COMPATIBILITY_CLASSES,
  COMPATIBILITY_POLICY,
  COMPATIBILITY_POLICY_LIMITS,
  COMPATIBILITY_POLICY_VERSION,
  COMPATIBILITY_SURFACE_IDS,
  MAX_COMPATIBILITY_CHANGE_ID_BYTES,
  MAX_COMPATIBILITY_SURFACE_ID_BYTES,
  classifyCompatibilityChange,
  validateCompatibilityPolicy,
} from "./compatibility-policy.js";
export type {
  CompatibilityChangeClassification,
  CompatibilityChangeClassificationResult,
  CompatibilityChangeMatrix,
  CompatibilityClass,
  CompatibilityEmergencyPolicy,
  CompatibilityMigrationPolicy,
  CompatibilityPolicy,
  CompatibilityPolicyValidationCode,
  CompatibilityPolicyValidationIssue,
  CompatibilityPolicyValidationResult,
  CompatibilitySemverPolicy,
  CompatibilitySurfaceId,
  CompatibilitySurfacePolicy,
  CompatibilityWindow,
} from "./compatibility-policy.js";

export {
  BASELINE_OUTPUT_SCHEMA_VERSION,
  EFFICIENCY_OUTPUT_SCHEMA_VERSION,
  JSON_OUTPUT_SCHEMA_VERSION,
  OUTPUT_COMPATIBILITY_CHANGES,
  OUTPUT_RECORD_KINDS,
  SARIF_OUTPUT_LEGACY_SCHEMA_VERSION,
  SARIF_OUTPUT_SCHEMA_VERSION,
  SARIF_SCHEMA_URI,
  SARIF_VERSION,
  STANDARDS_OUTPUT_SCHEMA_VERSION,
  TERMINAL_OUTPUT_SCHEMA_VERSION,
} from "./output-contracts.js";
export {
  MAX_BASELINE_ENTRIES,
  MAX_EFFICIENCY_RECOMMENDATIONS,
  MAX_OUTPUT_CONTAINER_ENTRIES,
  MAX_OUTPUT_KEY_BYTES,
  MAX_OUTPUT_STRING_BYTES,
  MAX_OUTPUT_TEXT_BYTES,
  MAX_OUTPUT_TEXT_CODE_POINTS,
  MAX_OUTPUT_TOTAL_STRING_BYTES,
  MAX_OUTPUT_VALUES,
  MAX_SARIF_RELATED_LOCATIONS,
  MAX_SARIF_RESULTS,
  MAX_SARIF_RULES,
  MAX_TERMINAL_LINES,
  classifyOutputCompatibility,
  detectSarifOutputProductVersion,
  isKnownOutputRecordKind,
  isNativeOutput,
  isSarifOutput,
  migrateSarifOutputV1,
  serializeNativeOutput,
  serializeSarifOutput,
  serializeTerminalOutput,
  validateBaselineOutput,
  validateEfficiencyOutput,
  validateNativeOutput,
  validateSarifOutput,
  validateSarifOutputV1,
  validateScanJsonOutput,
  validateStandardsOutput,
  validateTerminalOutput,
} from "./output-validation.js";
export {
  OUTPUT_REDACTION_MARKER,
  decodeSarifArtifactUri,
  encodeSarifArtifactUri,
  sanitizeOutputJson,
  sanitizeOutputText,
} from "./output-sanitization.js";
export type {
  BaselineEntry,
  BaselineOutput,
  BaselineProfileVersionIdentity,
  EfficiencyOutput,
  EfficiencyRecommendation,
  EfficiencyTokenStatistics,
  NativeOutputDocument,
  OutputCompatibilityChange,
  OutputCompatibilityResult,
  OutputRecordKind,
  OutputSerializationResult,
  OutputSummary,
  OutputValidationCode,
  OutputValidationIssue,
  OutputValidationResult,
  SarifLocation,
  SarifArtifactUri,
  SarifOutput,
  SarifOutputV1,
  SarifRegion,
  SarifRelatedLocation,
  SarifReportingDescriptor,
  SarifResult,
  SarifRun,
  SarifRunV1,
  SarifV1MigrationResult,
  ScanJsonOutput,
  ProfileVersionIdentity,
  StandardsArtifact,
  StandardsOutput,
  TerminalOutput,
} from "./output-contracts.js";

export {
  ACTIVATION_KINDS,
  AST_NODE_KINDS,
  IMPORT_KINDS,
  IMPORT_STATES,
  IMPORT_TARGET_KINDS,
  INSTRUCTION_IR_CONTRACT_VERSION,
  RESOLUTION_EVENT_KINDS,
} from "./ir-contracts.js";
export {
  isInstructionIr,
  sliceSourceRange,
  validateInstructionIr,
  validateSourceRange,
} from "./ir-validation.js";
export type {
  ActivationEvidenceRef,
  ActivationKind,
  ActivationRule,
  ActivationRuleId,
  ActivationSelector,
  AstNode,
  AstNodeId,
  AstNodeKind,
  ImportKind,
  ImportReference,
  ImportReferenceId,
  ImportState,
  ImportTargetKind,
  InstructionDocument,
  InstructionDocumentId,
  InstructionIr,
  InstructionIrValidationCode,
  InstructionIrValidationIssue,
  InstructionIrValidationResult,
  InstructionStatement,
  InstructionStatementId,
  JsonPrimitive,
  JsonValue,
  ResolutionEvent,
  ResolutionEventId,
  ResolutionEventKind,
  ResolutionSetting,
  ResolutionTarget,
  ResolutionTargetId,
  SourceDocument,
  SourceDocumentId,
  SourceParseState,
  SourcePosition,
  SourceRange,
  SourceRangeSliceResult,
  SourceRangeValidationResult,
  StatementClassification,
  StatementModality,
} from "./ir-contracts.js";

export {
  EVIDENCE_STATES,
  PROFILE_CATALOG_CONTRACT_VERSION,
  SUPPORT_STATES,
  UNCERTAINTY_STATES,
} from "./profile-contracts.js";
export { isProfileCatalog, validateProfileCatalog } from "./profile-validation.js";
export type {
  CapabilityClaim,
  CapabilityDefinition,
  CapabilityId,
  ClientProfile,
  ClientProfileId,
  ConditionalUncertainty,
  ContradictionAlternative,
  ContradictionUncertainty,
  DocumentFormat,
  DocumentFormatId,
  EvidenceRefId,
  EvidenceState,
  InvalidProfileCatalogResult,
  KnownUncertainty,
  ProfileCatalog,
  ProfileCatalogValidationCode,
  ProfileCatalogValidationIssue,
  ProfileCatalogValidationResult,
  SpecSnapshot,
  SpecSnapshotId,
  SpecSource,
  SpecSourceImmutability,
  SupportClaim,
  SupportState,
  Surface,
  SurfaceCapabilityClaim,
  SurfaceFormatSupport,
  SurfaceId,
  Uncertainty,
  UncertaintyState,
  UnknownUncertainty,
  ValidProfileCatalogResult,
} from "./profile-contracts.js";
export type { Clock, PathFlavor, PathService, RandomSource } from "./services.js";
