/** Non-negatable dependency, build, and cache exclusions shared by C03 and C04. */
export const BUILT_IN_IGNORE_PATTERNS: readonly string[] = Object.freeze([
  ".cache/",
  ".dart_tool/",
  ".git/",
  ".gradle/",
  ".next/",
  ".nuxt/",
  ".nx/",
  ".pnpm/",
  ".turbo/",
  ".venv/",
  ".yarn/cache/",
  "DerivedData/",
  "Pods/",
  "__pycache__/",
  "build/",
  "coverage/",
  "dist/",
  "node_modules/",
  "target/",
  "vendor/",
  "venv/",
]);
